
    <head>
        <meta charset="utf-8">
        <title>Paginatitel</title>
        <!-- <link rel="shortcut icon" href="" /> -->
        <meta name="description" content="omschrijving" />
        <meta name="author" content="Projectgroep 1241" />

        <!-- Style sheets -->
        <link rel="stylesheet" href="style.css" />

        <!-- Create HTML5 tags for IE compatibility> -->
        <!--[if lt IE 9]>
            <script src="js/html5.js"></script>
        <![endif]-->
    </head>
