<body>
        <div id="wrapper">
            <div id="header">Pagina titel</div>
            <nav id="topMenu">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="info.php">Info</a></li>
                    <li><a href="#">Agenda</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Event toevoegen</a></li>
                    <li><a href="#">Events accepteren</a></li>
                    <li><a href="#">Gebruikers beheren</a></li>
                    <li><a href="#">Login</a></li>
                </ul>
            </nav>
