
            <div id="footer">&copy; 2012 |
                <a href="http://validator.w3.org/check?uri=http%3A%2F%2Fwebsec.science.uva.nl%2Fwebdb1241%2F&amp;charset=%28detect+automatically%29&amp;doctype=Inline&amp;group=0">Validate HTML</a>
                | <a href="http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fwebsec.science.uva.nl%2Fwebdb1241%2F&amp;profile=css3&amp;usermedium=all&amp;warning=1&amp;vextwarning=&amp;lang=en">Validate CSS</a>
            </div>
