
            <aside id="sidebar_agenda">
                <form>
                    <label>Zoeken op woord</label>                    
                    <input name="eventName" placeholder="Naam of zoekterm" autofocus required>
                    
                    <label>Zoeken op catagorie</label>
                    <div id="checkbox_list">
                        <ul>
                            <li><input name="genre_pop" id="formCheckbox" type="checkbox" /> Pop</li>
                            <li><input name="genre_rock" id="formCheckbox" type="checkbox" /> Rock</li>
                            <li><input name="genre_metal" id="formCheckbox" type="checkbox" /> Metal</li>
                            <li><input name="genre_hiphop" id="formCheckbox" type="checkbox" /> Hiphop</li>
                            <li><input name="genre_blues" id="formCheckbox" type="checkbox" /> Blues</li>
                            <li><input name="genre_classic" id="formCheckbox" type="checkbox" /> Klassiek</li>
                            <li><input name="genre_church" id="formCheckbox" type="checkbox" /> Kerk</li>
                            <li><input name="genre_other" id="formCheckbox" type="checkbox" /> Overig</li>
                        </ul>
                    </div>
                </form>
            </aside>
